# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  NUGET_AUTHORS: 'Landorphan LLC, Michael Prochaska, Timothy Stockstill'
  NUGET_OWNERS: 'landorphan, mprochaska, tstockstill'
  NUGET_LICENSE: 'MIT'
  NUGET_COPYRIGHT: 'Copyright © 2019 - Landorphan, LLC.'

jobs:
- job: macos_build
  displayName: MacOS Build
  dependsOn: []
  pool:
    vmImage: 'macOS-latest'
  steps:
    - script: cmake -Bcmake-build-macos-release -H. -DCMAKE_BUILD_TYPE=release
      displayName: Generate Make Files
    - script: cmake --build cmake-build-macos-release --target all
      displayName: Build Project
    - script: mv ./cmake-build-macos-release/detach ./cmake-build-macos-release/macos-detach
      displayName: Rename detach to OS Specific name
    - task: CopyFiles@2
      displayName: 'Move Files to Staging Directory: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '$(Build.SourcesDirectory)/cmake-build-macos-release/macos-detach'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'macos'
        publishLocation: 'Container'

- job: linux_build
  displayName: Linux Build
  dependsOn: []
  pool:
    vmImage: 'ubuntu-16.04'
  steps: 
    - script: cmake -Bcmake-build-linux-release -H. -DCMAKE_BUILD_TYPE=release
      displayName: Generate Make Files
    - script: cmake --build cmake-build-linux-release --target all
      displayName: Build Project
    - script: mv ./cmake-build-linux-release/detach ./cmake-build-linux-release/linux-detach
      displayName: Rename detach to OS Specific name
    - task: CopyFiles@2
      displayName: 'Move Files to Staging Directory: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '$(Build.SourcesDirectory)/cmake-build-linux-release/linux-detach'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'linux'
        publishLocation: 'Container'
